Add most populars
GrayRoof/java-filmorate pull request #13
Opened 2022-11-24 22:42 UTC by NeuralPsy

2022-11-25 02:41 UTC, GrayRoof requested changes
Неплохая работа! у меня есть пара замечаний, которые касаются конфликта мерджа скорее всего. Я предлагаю всё-таки сначала смерджить к себе все имеющиеся изменения в develop (в твоем локальном репо нужно взять именно origin/develop или сначала в свой локальный develop затянуть изменения с origin)

2022-11-25 02:41 UTC, GrayRoof commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +import lombok.Builder;
наш ревюер, который и у меня был, сказал, что @Data и @Builder не должны быть указаны одновременно, т.к. они оба содержат в себе геттеры и это может вызывать конфликты. 
на общем ревью он так же это отметит, поэтому стоит обойтись чем-то одним

2022-11-25 02:41 UTC, GrayRoof commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> -            addExtraFilmData(films);
Мы договорились, что имеет смысл вместо 2 повторяющихся вызовов load иметь 1 вызов addExtraFilmData, который бы прогружал genres

2022-11-25 02:41 UTC, GrayRoof commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +package ru.yandex.practicum.filmorate.storage;
Этот класс решено было удалить. Максим проделал большую работу по рефакторингу. Видимо, ты таки не влил себе его изменения

2022-11-25 02:41 UTC, GrayRoof commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +        genreStorage.getGenresByFilmId(filmId).forEach(genre -> genres.add(genre));
При таком способе мэйкать фильм получается так, что для каждого фильма программа делает доп запрос в БД для получения жанров. Т.е., имея коллекцию в 100 фильмов, программа делает +100 доп запросов для формирования коллекции. Чтобы этого не происходило, Лев написал метод load, который 1 раз загружает в кеш все жанры, из которых потом все это счастье биндится в сущность фильм. Это должно происходить на уровне сервиса, т.к. его ревьюер делал уточнение по этому поводу, что, мол, стораджи не должны зависеть друг от друга

2022-11-25 08:47 UTC, terekhovmv commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +import lombok.Builder;
Мне наш ревьювер то же самое писал :).

2022-11-25 11:17 UTC, GrayRoof approved these changes

2022-11-25 11:45 UTC, LevKlimenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +import lombok.Builder;
Странно что мой на это внимание не обратил..

2022-11-25 11:47 UTC, terekhovmv requested changes

2022-11-25 11:47 UTC, terekhovmv commented on src/main/java/ru/yandex/practicum/filmorate/SqlQueries.java
> +}
Выносить константы это почти всегда хорошо. Но нужны ли они здесь в этом случае? Если не предполагается их использовать за пределами DBFilmStorage, то лучше их писать по месту, тогда читающему код db-реализации хранилища будет более очевидно, куда какие подстановки значений идут. Еще пакет, в котором расположен этот файл слишком "крут" для констант db-реализации хранилища. Все, связанной с БД у нас в storage.dao.

2022-11-25 11:47 UTC, terekhovmv commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final DBGenreStorage dbGenreStorage;
Здесь нужно использовать интерфейс GenreStorage.

2022-11-25 11:47 UTC, terekhovmv commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                       GenreValidator genreValidator) {
`@Qualifier(UsedStorageConsts.QUALIFIER)` указывает на актуальный дефолтный qualifier (сейчас указаны несуществующие), и хотелось бы видеть тут интерфейсы (изменения из develop залились неверно).

2022-11-25 11:47 UTC, terekhovmv commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final DBDirectorStorage directorStorage;
Здесь нужно использовать интерфейс DirectorStorage.

2022-11-25 11:47 UTC, terekhovmv commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
Предлагаю написать функцию Integer getRequestedNumber(String requestedNumber) , которая проверит на равенство all с учетом trim() и капитализации латиницы, вернет null если там что-то похожее на all, число, если там число или бросит исключение от конвертации Integer.parseInt. Тогда эта функция сильно упростится, в не будет 6 штук equals("all") и Integer.parseInt.

2022-11-25 11:53 UTC, LevKlimenko approved these changes
Исправить что написано в комментах и все ок)

2022-11-25 12:26 UTC, NeuralPsy commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +import lombok.Builder;
Точно. Исправил)

2022-11-25 12:33 UTC, NeuralPsy commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +package ru.yandex.practicum.filmorate.storage;
Done

2022-11-25 14:02 UTC, Koss-Koss approved these changes

2022-11-26 01:41 UTC, GrayRoof approved these changes
Спасибо за правки! Ты молодец!

2022-11-26 02:25 UTC, terekhovmv commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +
@GrayRoof , для пост-рефакторинга --
1. порядок аргументов тут немного поплыл.
2. возможно, можно 4 метода все-таки свернуть в 1:
Collection<Film> getMostPopular(Integer filteredGenre, Integer filteredYear, int count);

2022-11-26 02:28 UTC, terekhovmv approved these changes

2022-11-26 02:33 UTC, GrayRoof approved these changes

2022-11-26 02:33 UTC, GrayRoof commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +
Поняла, сделаю

2022-11-26 02:34 UTC, merged