Add feed
GrayRoof/java-filmorate pull request #17
Opened 2022-11-25 06:06 UTC by GrayRoof

2022-11-25 08:33 UTC, LevKlimenko approved these changes

2022-11-25 08:33 UTC, LevKlimenko commented on src/main/java/ru/yandex/practicum/filmorate/model/AllowedFeedEvents.java
> +
Желательно избавляться от пустых строк)

2022-11-25 08:33 UTC, LevKlimenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBUserStorage.java
> +    private User makeUser(ResultSet rs) throws SQLException {
Молодец что правильный порядок методов организовала, согласно приватности

2022-11-25 09:25 UTC, Koss-Koss approved these changes

2022-11-25 09:27 UTC, Koss-Koss commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBUserStorage.java
> +    private User makeUser(ResultSet rs) throws SQLException {
На словах лента была проста и понятна. А код читал больше часа. Отличная работа!

2022-11-25 09:27 UTC, Koss-Koss commented
На словах лента была проста и понятна. А код читал больше часа. Отличная работа!

2022-11-25 09:32 UTC, GrayRoof commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBUserStorage.java
> +    private User makeUser(ResultSet rs) throws SQLException {
да, после того, как всё вольем, кого-то одного посадим всё приводить в чистоту. нэйминг, строки пустые, импорты висящие и тд. скорее всего меня и посадим хД

2022-11-25 09:34 UTC, GrayRoof commented on src/main/java/ru/yandex/practicum/filmorate/model/AllowedFeedEvents.java
> +
Да, ты прав! исправим после того, как все вольются. рефакторинг произведем не только по пустым строкам, но и по другим аспектам стиля

2022-11-25 12:22 UTC, NeuralPsy approved these changes

2022-11-25 13:55 UTC, terekhovmv commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFeedStorage.java
> +                "where USERID = ?";
Философский вопрос -- действительно ли нужно хранить эти enums (operations, eventType) в БД?

2022-11-25 14:00 UTC, GrayRoof commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFeedStorage.java
> +                "where USERID = ?";
Это в рамках нормализации БД как я это понимаю. сама БД ограничивает запись заданными перечнями значений.

2022-11-25 14:04 UTC, terekhovmv commented on src/test/java/ru/yandex/practicum/filmorate/storage/dao/DBTestQueryConstants.java
> +}
Полезная константа! Возможно, на 100500 шаге рефакторинга мы сделаем компонент с интерфейсом EnvCleaner и методом clean(). И в DB реализации этого интерфейса мы перенесем этот скрипт в clena() и будем исполнять :).

2022-11-25 14:06 UTC, terekhovmv commented on src/test/java/ru/yandex/practicum/filmorate/storage/dao/DBTestQueryConstants.java
> +}
Меня до сих пор смущает SQL пусть даже спрятанный за константой в тестах на сервисы. На месте заказчика я бы придирался.

2022-11-25 14:06 UTC, terekhovmv commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserStorageTestHelper.java
> +                        String.format("email-%d@test.test", idx),
👍

2022-11-25 14:09 UTC, terekhovmv commented on src/test/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorageTest.java
>          jdbcTemplate.update("DELETE FROM likes;");
Не стоит ли тогда tearDown, если очищаем окружение до?

2022-11-25 14:09 UTC, terekhovmv commented on src/test/java/ru/yandex/practicum/filmorate/storage/dao/DBReviewStorageTest.java
>          jdbcTemplate.update("DELETE FROM friendship;");
Не стоит ли тогда tearDown, если очищаем окружение до?

2022-11-25 14:10 UTC, terekhovmv commented on src/test/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorageTest.java
>          jdbcTemplate.update("DELETE FROM likes;");
Это касается всех тестов.

2022-11-25 14:11 UTC, terekhovmv requested changes
См. замечания по setUp/tearDown логике.

2022-11-25 16:27 UTC, GrayRoof commented on src/test/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorageTest.java
>          jdbcTemplate.update("DELETE FROM likes;");
имеешь в виду удалить? Да, стоит)

2022-11-26 18:27 UTC, Koss-Koss approved these changes
Кропотливо!

2022-11-26 18:59 UTC, merged