Add reviews
GrayRoof/java-filmorate pull request #18
Opened 2022-11-25 10:31 UTC by NeuralPsy

The fix is ready

2022-11-25 11:15 UTC, GrayRoof approved these changes

2022-11-25 11:15 UTC, GrayRoof commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        return service.addLike(Integer.parseInt(id), Integer.parseInt(userId));
Если вместо числа в параметре прилетит текст, то parseInt выбросит исключение. У меня на этот счет есть спец метод 
`private Integer intFromString(final String supposedInt) {
        try {
            return Integer.valueOf(supposedInt);
        } catch (NumberFormatException exception) {
            return Integer.MIN_VALUE;
        }
    }`

не знаю, будут ли на ревью придираться по этому поводу

2022-11-25 11:15 UTC, GrayRoof commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBReviewStorage.java.orig
> +    public Review addLike(Integer reviewId, Integer userId) {
мне нужна пояснительная бригада)

2022-11-25 11:25 UTC, LevKlimenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBReviewStorage.java.orig
> +    public Review addLike(Integer reviewId, Integer userId) {
почему то не учитывается пользователь который поставил лайк

2022-11-25 11:41 UTC, LevKlimenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        return service.addLike(Integer.parseInt(id), Integer.parseInt(userId));
а почему бы не использовать Long в @PathVariable? Спринг автоматически сделать конвертацию.
Одновременно можно сделать проверку на класс принимаемого значения. Сейчас проверил в яндекс-поиске на значение странице поиска буквенного выражения. В случае если значение p.class==String.class -> p=0L(Открывается первая страница)

2022-11-25 11:41 UTC, LevKlimenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBReviewStorage.java
> +        String sqlQuery2 = "insert into useful (reviewId, userId, useful) values (?, ?, ?)";
На мой взгляд название запроса в таком случае лучше изменить на sqlQueryUseful, чтобы в дальнейшем не пытаться понять что за название имеет индекс 2

2022-11-25 11:41 UTC, LevKlimenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBReviewStorage.java
> +        String sqlQuery2 = "delete from useful where ReviewID = ? and userid = ? and useful = ?";
Здесь так же надо изменить название,т.к. проще будет определить что это за запрос
В остальных случаях тоже надо поменять.

2022-11-25 11:41 UTC, LevKlimenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBReviewStorage.java.orig
> +<<<<<<< HEAD
Здесь так же, как и выше, надо определиться в количестве принимаемых параметров.

2022-11-25 11:41 UTC, LevKlimenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBReviewStorage.java.orig
> +        if (filmId.equals("all")) {
Если метод у тебя Collection<Review> getAll() то он не должен получать значение по id, для этого необходим метод 
Collection<Review> getByFilmId(Integer filmId,int count)

2022-11-25 11:41 UTC, LevKlimenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBReviewStorage.java.orig
> +        return getReview(reviewId);
вопрос в функциональности.
Есть ли смысл возвращать ревью, или необходим лишь возврат "True" or "False"?

2022-11-25 12:22 UTC, terekhovmv requested changes

2022-11-25 12:22 UTC, terekhovmv commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBReviewStorage.java.orig
> +    public Review addLike(Integer reviewId, Integer userId) {
Этот файл следует удалить, это orig-файл, артефакт мержевания с конфликтами, он не должен попадать в систему контроля версий,  и в сборке он не участвует. Ревьювить его можно, но не нужно :).

2022-11-25 12:22 UTC, terekhovmv commented on src/test/java/ru/yandex/practicum/filmorate/storage/dao/DBReviewStorageTest.java
> +        reviewStorage.removeLike(1, 1);
Тут 1 и 1 выглядят как magic numbers. непонятно, откуда взялись :(.
То же самое внутри addLike (там есть и filmId, и userId), но после добавления review мы используется 1 вместо review.getId. Использование переменных сделает наши тесты менее чувствительными к изменениям.
Мне кажется допустимым для тестов, да и то не самый хороший вариант, использовать числовые id (не очень большие -- 1,2,3) для указания mpaId и genreId, поскольку соотв. таблицы предзаполнены и немодифицируемы (по крайней мере на данный момент).

2022-11-25 12:22 UTC, terekhovmv commented on src/main/java/ru/yandex/practicum/filmorate/validator/ReviewValidator.java
> +
Пакет с этим классом расположен вне пакета db-реализации хранилища. Думаю, будет правильнее перенести boolean-методы проверки в интерфейс review-хранилища, поскольку оно уже науилучшим образом осведомлено о таблицах, обслуживающих эту функциональность. Потом можно инжектировать ReviewService в этот класс или устранить этот класс, перенеся валидацию с исключениями в сервис.

2022-11-25 12:22 UTC, terekhovmv commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            return storage.addDislike(reviewId, userId);
Если бросить пить, а потом запить снова, то ничего не изменится. Может быть тогда и не бросать? :)
Аналогично в addLike

2022-11-25 12:22 UTC, terekhovmv commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBReviewStorage.java
> +        jdbcTemplate.update(sqlQuery, changeUsefulValue(reviewId, false), reviewId);
Тут получаются два запроса к базе -- вычисление нового useful и выставление useful. Можно совместить.

2022-11-25 13:29 UTC, Koss-Koss commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        return service.addLike(Integer.parseInt(id), Integer.parseInt(userId));
Я бы передавал в сервис как есть , в виде строки, а сервис пускай проверяет, текст там или действительно число

2022-11-25 13:39 UTC, LevKlimenko approved these changes

2022-11-25 13:44 UTC, terekhovmv requested changes
Хорошо, что сделал фикс, замечания в комментах выше.

2022-11-25 14:01 UTC, Koss-Koss approved these changes

2022-11-25 18:07 UTC, NeuralPsy commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        return service.addLike(Integer.parseInt(id), Integer.parseInt(userId));
Да. Действительно, можно ведь было и лонги указать. Переделал. Но не совсем так. Указал Integer.

2022-11-26 01:31 UTC, GrayRoof approved these changes
Отличная работа!

2022-11-26 02:30 UTC, terekhovmv approved these changes

2022-11-26 02:37 UTC, merged